### ISSUE TITLE
Certificates are generated for all subdomains despite *.example.com setting

### ISSUE THREAD

**Issue by guyromb** [Kong/kong-plugin-acme#11]
Plugin domains configuration is set to:
```
"domains": [
      "*.example.com",
      "example.com"
    ],
````

Expected to generate for configured domains. Instead it generates for www.example.com and example.com.

Also, next time subdomain1.exmaple.com is requested, it will generate a certificate for subdomain1.example.com. This will cause issues with Letsencrypt when you have many sub domains (monthly limit reached). Instead it should only generate *.example.com (supported).

**Comment by fffonion** [comment]
Hi,
Wildcard certificates are supported by dns verifications, which this plugin or current model won't support. The star symbol in domains config is only to match domains but not actually use in cert.

The Let's Encrypt rate limit for cert per domain is 50 per week, meaning you can have 50 subdomain certificate for each example.com every week, which I assume will be sufficient for most users. If you saw a rate limit error in error log, it's most likely some other limit.

**Comment by fffonion** [comment]
Consider this resolved, please feel free to reopen if you have other questions : )

**Comment by portothree** [comment]
Hello @guyromb 
I'm facing the same issue right now, receiving the following error:
`2021/01/07 15:28:41 [error] 29#0: *116 [kong] handler.lua:109 failed to update certificate: could not create certificate: failed to create new order: Error creating new order :: too many certificates already issued for exact set of domains: api.example.pt: see https://letsencrypt.org/docs/rate-limits/, context: ngx.timer, client: 94.63.157.31, server: 0.0.0.0:8443`.

Did you find a solution to create only one cert for the main domain, in this case `example.pt`?
