### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by OneideLuizSchneider** [Kong/kong-plugin-acme#18]
Hi,
I'm trying to figure out what is happening, my configuration looks well, I tested with the commands on the readme, but it doesn't run or generate the certificate. I don't know why.
And I'm using the plugin in database mode.

```
{
    "api_uri": "https://acme-v02.api.letsencrypt.org",
    "domains": [
        "subdomain.domain.site"
    ],
    "storage": "shm",
    "cert_type": "rsa",
    "tos_accepted": true,
    "account_email": "myemail@mydomain.com",
    "storage_config": {
        "shm": {
            "shm_name": "kong"
        },
        "kong": {},
        "redis": {
            "auth": null,
            "host": null,
            "port": null,
            "database": null
        },
        "vault": {
            "host": null,
            "port": null,
            "https": true,
            "token": null,
            "kv_path": null,
            "timeout": null
        },
        "consul": {
            "host": null,
            "port": null,
            "https": true,
            "token": null,
            "kv_path": null,
            "timeout": null
        }
    },
    "renew_threshold_days": 14
}
```

<img width="956" alt="Screen Shot 2020-05-11 at 18 48 53" src="https://user-images.githubusercontent.com/5761239/81615560-2effc100-93b8-11ea-90b4-192598bfb806.png">

<img width="956" alt="Screen Shot 2020-05-11 at 18 34 15" src="https://user-images.githubusercontent.com/5761239/81615180-8ea99c80-93b7-11ea-9ea7-78409a8c6b4e.png">

**Comment by OneideLuizSchneider** [comment]
I just forgot to run the generate command.
`curl https://mydomain.com -k`

**Comment by aogg** [comment]
curl https://mydomain.com -k

Created successfully but still can't work
