### ISSUE TITLE
remove the BasePlugin dependency

### ISSUE THREAD

**Issue by hishamhm** [Kong/kong-plugin-acme#2]
Since Kong 1.2, the `BasePlugin` instantiation is no longer necessary and simply adds an unnecessary indirection in plugin calls.

See https://github.com/Kong/kong/commit/a29c3553f43dd53cfc78d618e653e3e7ae484dbb

**Comment by fffonion** [comment]
@hishamhm Thank you pointing this out! I will push a commit to fix this.

**Comment by fffonion** [comment]
closing as fixed in #3
