### ISSUE TITLE
Question: certs renew

### ISSUE THREAD

**Issue by Xplouder** [Kong/kong-plugin-acme#20]
Hi,

I noticed that accordingly with the logs, there was no attempt to renew the certificates. Some of my domains will expire in 13 days so I believe that the automatic renew is disabled or some of my configs are wrong.
How the renewal internally work? I couldn't find reference for a cron so I believe is there some kind of scheduler.

Kong version: 2.0.3 with acme plugin active

My acme plugin config extracted from Postgres database:
```
{
   "api_uri":"https://acme-v02.api.letsencrypt.org",
   "domains":[
      "my_domains_are_listed_here"
   ],
   "storage":"shm",
   "cert_type":"rsa",
   "tos_accepted":true,
   "account_email":"my_is_email_here",
   "storage_config":{
      "shm":{
         "shm_name":"kong"
      },
      "kong":{

      },
      "redis":{
         "auth":null,
         "host":null,
         "port":null,
         "database":null
      },
      "vault":{
         "host":null,
         "port":null,
         "https":true,
         "token":null,
         "kv_path":null,
         "timeout":null
      },
      "consul":{
         "host":null,
         "port":null,
         "https":true,
         "token":null,
         "kv_path":null,
         "timeout":null
      }
   },
   "renew_threshold_days":30
}
```

I also noticed that the table `acme_storage` is empty. I created a new domain and generated a certificate for it to ensure that the reason for the empty table was not a bad db migration (which I did in the past).

**Comment by fffonion** [comment]
Hi @Xplouder, since you are using the `"shm"` storage, all renew configs are stored in your shm not in db (hence `acme_storage` table is empty), which might be the case here since it doesn't survive between restarts. Also usually renewal messages are shown as info level, you will need to set correct log level if you want to check if renewal really runs.

The default value for storage is `"shm"` mainly to consists with dbless mode. I'll add a note in the readme about this.

**Comment by fffonion** [comment]
> How the renewal internally work? I couldn't find reference for a cron so I believe is there some kind of scheduler.

Basically it's a openresty timer that runs every 24h, that checks for "renew configs" in the configured storage. Then it checks each certificate if it's due for renewal. You'll be able to see the last timestamp renewal scheduler runs by getting the [kong_acme:renew_last_run](https://github.com/Kong/kong-plugin-acme/blob/master/kong/plugins/acme/client.lua#L11) key from configured storage.

**Comment by Xplouder** [comment]
@fffonion Thanks for the response. So, since I'm using Postgres, which value for ```"storage"``` config I should use? I believe "kong" is the one. 
Also, setting this correctly, the renew jobs will start work correctly? If not, what I have to do?

**Comment by fffonion** [comment]
@Xplouder Yes, simply change it to `"kong"` and it should work. You can set a very high `renew_threshold_days` and see if it correctly renews in one day (or even change the code to let the timer run less than 1 day https://github.com/Kong/kong-plugin-acme/blob/master/kong/plugins/acme/handler.lua#L54). If it doesn't work try set kong's log_level to `debug` and see it there's anything interesting in the output.

**Comment by Xplouder** [comment]
Aight, I'll post here the updates, probably tomorrow.

**Comment by Xplouder** [comment]
I will try to describe what happened:

I had old certs in the database, however, they were created before the change storage config from `shm` to `kong`

The command `curl https://<my_domain> -k` (using an old domain that could be renewed) was producing the following logs:
```
[debug] 22#0: *9576 [kong] handler.lua:89 [acme] ignoring because non-default cert is served
[debug] 22#0: *9575 [lua] init.lua:818: balancer(): setting address (try 1): <my_ip>:8001
- - [23/May/2020:01:29:01 +0000] "GET / HTTP/2.0" 403 153 "-" "curl/7.58.0"
```

The `acme_storage` table remained the same (just few entries that came in when I registered a new test domain after storage config change), no matter how many times the renew timer pops up, producing this log:
```
[info] 22#0: *10430 [kong] client.lua:326 renew storage configured in acme plugin: ee8cd615-32c6-4bfe-8022-b3c1c7dcd49f, context: ngx.timer
[debug] 22#0: *10430 [lua] events.lua:211: do_event(): worker-events: handling event; source=dao:crud, event=update, pid=nil, data=table: 0x7f62ce4f0b08
[debug] 22#0: *10430 [lua] cache.lua:300: invalidate_local(): [DB cache] invalidating (local): 'acme_storage:kong_acme:renew_last_run::::'
[debug] 22#0: *10430 [lua] events.lua:211: do_event_json(): worker-events: handling event; source=mlcache, event=mlcache:invalidations:kong_db_cache, pid=22, data=acme_storage:kong_acme:renew_last_run::::
[debug] 22#0: *10430 [lua] cache.lua:321: invalidate(): [DB cache] broadcasting (cluster) invalidation for key: 'acme_storage:kong_acme:renew_last_run::::' with delay: 'none'
[debug] 22#0: *10430 [lua] events.lua:211: do_event(): worker-events: handling event; source=crud, event=acme_storage, pid=nil, data=table: 0x7f62ce4f0b08
[debug] 22#0: *10430 [lua] events.lua:211: do_event(): worker-events: handling event; source=crud, event=acme_storage:update, pid=nil, data=table: 0x7f62ce4f0b08
[info] 22#0: *10430 [kong] client.lua:266 certificate for <my_test_domain> is not due for renewal, context: ngx.timer
``` 

What I did to fix the old domains:
- remove old generated certificates
- do the curl command `curl https://<my_domain> -k` for each one

**(possible bug)** I also noticed that after removing the test domain created from renew route, acme plugin whitelist settings and the respective certificate, the acme timer keep trying to check if the domain able to be renewed. So I checked `acme_storage` table and the actions I did (described before) to delete the domain, it did not clear the table which may generate unnecessary certs.

**Comment by fffonion** [comment]
The behaviour is expected: when moving storage kong will lost knowledge of renew configs in the previous storage.

> it did not clear the table which may generate unnecessary certs

You are right, the plugin indeed doesn't clear the renew config when the cert is deleted, though theoretically it will fail gracefully and no new cert will be created. I will open a PR to fix this. 

Thanks for reporting this!

**Comment by Xplouder** [comment]
Thanks for all the help!

**Comment by aogg** [comment]
Which version of Kong corresponds to 

https://hub.docker.com/_/kong

2.3.2-alpine, 2.3-alpine, 2.3.2, 2.3, 2, alpine, latest
2.3.2-ubuntu, 2.3-ubuntu, ubuntu
2.3.2-centos, 2.3-centos, centos
2.2.1-alpine, 2.2-alpine, 2.2.0, 2.2
2.2.1-ubuntu, 2.2-ubuntu
2.2.1-centos, 2.2-centos
2.1.4-alpine, 2.1-alpine, 2.1.4, 2.1
2.1.4-ubuntu, 2.1-ubuntu
2.1.4-centos, 2.1-centos
2.0.5-alpine, 2.0.5, 2.0
2.0.5-ubuntu, 2.0-ubuntu
2.0.5-centos, 2.0-centos
