### ISSUE TITLE
UNIQUE violation detected

### ISSUE THREAD

**Issue by Rahimianes** [Kong/kong-plugin-acme#42]
I have below error when I want to create a new certificate .

{"message":"UNIQUE violation detected on '{consumer=null,name=\"acme\",route=null,service=null}'","name":"unique constraint violation","fields":{"service":null,"name":"acme","route":null,"consumer":null},"code":5

the installation was followed with this below guide:
https://docs.konghq.com/hub/kong-inc/acme/#create-certificates
but I can't create and enable certificate with any addresses, you can see errors :

$ curl http://localhost:8001/service \
>         -d name=acme-dummy \
>         -d url=http://127.0.0.1:65535
**{"message":"Not found"}**

$ curl http://localhost:8001/routes \
        -d name=acme-dummy \
        -d paths[]=/.well-known/acme-challenge \
        -d service.name=acme-dummy

**{"id":"85cc0abe-e21b-4c9c-962c-42a898054b56","path_handling":"v0","paths":["\/.well-known\/acme-challenge"],"destinations":null,"headers":null,"protocols":["http","https"],"created_at":1596298015,"snis":null,"service":{"id":"8e6a71a5-1ca7-48c2-b090-2c67e770006c"},"name":"acme-dummy","strip_path":true,"preserve_host":false,"regex_priority":0,"updated_at":1596298015,"sources":null,"methods":null,"https_redirect_status_code":426,"hosts":null,"tags":null}**

$ curl http://localhost:8001/plugins \
        -d name=acme \
        -d config.account_email=my@email.com \
        -d config.tos_accepted=true \
        -d config.domains[]=my.secret.domains.com

**{"message":"UNIQUE violation detected on '{consumer=null,name=\"acme\",route=null,service=null}'","name":"unique constraint violation","fields":{"service":null,"name":"acme","route":null,"consumer":null},"code":5}**

what is the problem?
how can I resolve this problem?
thanks

**Comment by fffonion** [comment]
Hi @Rahimianes , that means you already have a global `acme` plugin configured. You can check all configured plugins by sending `curl localhost:8001/plugins`.

**Comment by fffonion** [comment]
Closing this as it's not an issue with plugin or Kong but rather configuration issue. Please reopen if you run into other issues.
