### ISSUE TITLE
Failed to renew certs when http-01 fails for a domain

### ISSUE THREAD

**Issue by vijithv** [Kong/kong-plugin-acme#48]
We have noticed that _some_ of our domain certificates aren't getting renewed by the scheduled worker process but works fine when we use the `/acme -d [domain]` endpoint (version 0.2.10).

Looking at the code for `client.renew_certificate()`, it seems the following line of code returns from the loop when `update_certificate()` fails for a domain
https://github.com/Kong/kong-plugin-acme/blob/master/kong/plugins/acme/client.lua#L367

For us this was failing due to a http-01 challenge failure as the particular domain isn't pointing to us anymore. 

Shouldn't it be continuing with the loop rather than returning, so that it renews the rest of the domains in the storage? Or is there a recommended alternative for handling this case?

**Comment by fffonion** [comment]
@vijithv thanks for reporting this. Yes this is by design, as failure of one domain may be resulted from bad configuration and we don't want to blindly run into rate limiting. This will be made better in following versions when we introduce a backoff.

**Comment by vijithv** [comment]
@fffonion thanks for the quick reply

**Comment by fffonion** [comment]
@vijithv There'll be a new config `config.fail_backoff_minutes` that allow you to continue after failure in next release of plugin.
