### ISSUE TITLE
Problems renewing the certificates

### ISSUE THREAD

**Issue by OneideLuizSchneider** [Kong/kong-plugin-acme#57]
Hi
I have some problems with renewing my certificates.

When I create a new one, it works well because I still don't have a route to redirect the requests to my cluster.
Once I create the route(on Kong Service), the requests will be redirected, after this, the renewing doesn't work.

What I do to solve this is removing the route(on Kong Service), and remove the certificate, and create it again.

I'm tried to force and renew with` curl http://localhost:8001/acme -d host=domain.com`, and I receive the request from Letsencrypt. But didn't renew the certificate(below is a picture).
<img width="2393" alt="Screen Shot 2020-10-17 at 12 30 59" src="https://user-images.githubusercontent.com/5761239/96347142-f904ee00-1075-11eb-9bdb-f3f36abe9515.png">

Is there any other option to solve this?

I'm using Kong with Docker, version 2.1.4, and ACME with Redis.
Conf.:
```
docker run -d --name kong \
     --network=kong-net \
     --restart unless-stopped \
     -e "KONG_DATABASE=postgres" \
     -e "KONG_PG_HOST=127.0.0.1" \
     -e "KONG_PG_PORT=5432" \
     -e "KONG_PG_PASSWORD=pass" \
     -e "KONG_CASSANDRA_CONTACT_POINTS=127.0.0.1" \
     -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
     -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
     -e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
     -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
     -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" \
     -e "KONG_PROXY_LISTEN=0.0.0.0:80, 0.0.0.0:443 ssl" \
     -e "KONG_NGINX_PROXY_PROXY_BUFFER_SIZE=256k" \
     -e "KONG_NGINX_PROXY_PROXY_BUFFERS=64 512k" \
     -e "KONG_NGINX_PROXY_PROXY_BUSY_BUFFERS_SIZE=512k" \
     -e "KONG_LUA_SSL_TRUSTED_CERTIFICATE=/etc/ssl/certs/ca-certificates.crt" \
     -p 80:80 \
     -p 443:443 \
     -p 8001:8001 \
     kong:2.1.4
```

**Comment by fffonion** [comment]
Hi @OneideLuizSchneider this is a known bug when using with kong >= 2.0.5 in dbless mode. There's a fix #55 but haven't been released with Kong yet. For now your can install the new plugin version with `luarocks install lua-resty-acme --force` and built a new image.

**Comment by OneideLuizSchneider** [comment]
Hi @fffonion, thanks for your answer.
I saw the other issues here, and they are similar.

But I think it is another problem because it just happens when I have a route(on Kong Service) and redirect the requests, when I remove the route(on Kong Service) and force and renew, It works well.

**Comment by OneideLuizSchneider** [comment]
Hi @fffonion 
I found the 'problem' and when It happens.

It just happens when I have just **HTTPS** activate on the Route, when I let with **HTTP** and **HTTPS** than It works well.

How I figured this out, when I run the **test_http_challenge_flow** with and without HTTP on the Route.

- With http on the Route:
`curl http://localhost:8001/acme -d host=domain.com -d test_http_challenge_flow=true `
`{"message":"sanity test for host domain.com passed"}`

- Without HTTP on the Route:
`curl http://localhost:8001/acme -d host=domain.com -d test_http_challenge_flow=true`
`{"message":"problem found running sanity check for domain.com: unexpected response found :<html>\r\n<head><title>301 Moved Permanently<\/title><\/head>\r\n<body>\r\n<center><h1>301 Moved Permanently<\/h1><\/center>\r\n<\/body>\r\n<\/html>\r\n, unexpected status code: 301"}`

Do you have an idea to fix this?
Because all the requests must be HTTPS, in my case. And when someone makes an HTTP request, kong redirects to HTTPS when I don't have HTTP conf on the Route.

**Comment by fffonion** [comment]
@OneideLuizSchneider That's good observation! Yes you will need the challenge request to properly routable. If your existing route are all HTTPS, you can create a dummy route that accepts the acme http challenge only as in https://github.com/Kong/kong-plugin-acme#enable-the-plugin

**Comment by OneideLuizSchneider** [comment]
@fffonion I have the dummy(HTTP) route as Global, and works well. 
But when renew, Letsencrypt sends the request to the domain as you can see on the first comment here.
And because I have the route(on Kong Service) that match, he will use this one.

**Comment by fffonion** [comment]
@OneideLuizSchneider There's no difference on what Let's Encrypt server will request between a new cert and a renewal, they are validated on same path. If I understand it correctly, it's likely a route priority issue, try create a route that will match the /well-known/.acme-challenge/ path on the domain you are interested but with HTTP protocol.

**Comment by OneideLuizSchneider** [comment]
@fffonion Yep, I tried this before, and works as well.
But I thought maybe there was something more different/simple, just because I have more than 60 domains and everyone has subdomains. 
Would be much easier if I could create just one dummy route for` /.well-known/.acme-challenge`.
But it's ok, I appreciate your help, thanks a lot.
