### ISSUE TITLE
plugin not found 2.0.0rc1

### ISSUE THREAD

**Issue by lukasa1993** [Kong/kong-plugin-acme#6]
trying to use plugin on 2.0.0 kong i can see it exists in racks folder but when i calll kong admin to enable it it says couldnt be found do i need to enable it some other way?

**Comment by fffonion** [comment]
Hi @lukasa1993 , the acme plugin is not a `bundled` plugin with Kong. You need to enable it explictly, try add the following line to your kong.conf:
```
plugins=bundled,acme
```

**Comment by lukasa1993** [comment]
thank you
