### ISSUE TITLE
Failing to generate ACME certificates

### ISSUE THREAD

**Issue by iacapuca** [Kong/kong-plugin-acme#61]
Hello, currently I have a Kong API Gateway running through my single node docker swarm with a few API’s behind it, I’m totally able to reach each of the trough each route, but only through HTTP.
I have installed the ACME plugin, although it’s not clear to me how I should configure it in order to trigger the creation of the certificates for each service.

If I run:

`curl http://127.0.0.1:8001/acme -d host=mydomain.com -d test_http_challenge_flow=true`
It returns:

`{"message":"sanity test for host mydomain.com passed"}`
But, if I try

`curl http://127.0.0.1:8001/acme -d host=mydomain.com`
It returns:

`{"message":"failed to update certificate: could not create certificate: challenge invalid: http-01: invalid: Invalid response from http:\/\/mydomain\/.well-known\/acme-challenge\/cfbSYzt39OWFm9bObeoL3T7gidAVLRmn1dm7iscz15s [myserverip]: 404"}`

This is the container log:
```
_kong.2.u8d8srbp9lcy@vps-2c1ec9df    |  2020/12/11 15:28:38 [warn] 21#0: *5536 [lua] http-01.lua:54: serve_challenge(): no corresponding response found for YCRxFSgSzaaWlT3kohB-WzxWiVpExHRacdFNXy3xroM, client: 10.0.0.2, server: kong, request: "GET /.well-known/acme-challenge/YCRxFSgSzaaWlT3kohB-WzxWiVpExHRacdFNXy3xroM HTTP/1.1", host: "mydomain.com
kong_kong.2.u8d8srbp9lcy@vps-2c1ec9df    |  10.0.0.2 - - [11/Dec/2020:15:28:38 +0000] "GET /.well-known/acme-challenge/YCRxFSgSzaaWlT3kohB-WzxWiVpExHRacdFNXy3xroM HTTP/1.1" 404 27 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
```

**Comment by fffonion** [comment]
@iacapuca could you share your kong/kong enterprise version and the plugin's config? and if you install the plugin manually, could you also share the plugin version?

**Comment by iacapuca** [comment]
My Kong is not the enterprise one, and I'm using the latest image from docker hub

`
{
  "created_at": 1607698670,
  "id": "ebb6e3b3-6120-47bc-b962-b83c6f69f6a2",
  "tags": null,
  "enabled": true,
  "protocols": [
    "grpc",
    "grpcs",
    "http",
    "https"
  ],
  "name": "acme",
  "consumer": null,
  "service": null,
  "route": null,
  "config": {
    "api_uri": "https://acme-v02.api.letsencrypt.org/directory",
    "storage": "shm",
    "storage_config": {
      "redis": {
        "auth": null,
        "port": null,
        "database": null,
        "host": null
      },
      "shm": {
        "shm_name": "kong"
      },
      "vault": {
        "host": null,
        "port": null,
        "token": null,
        "timeout": null,
        "https": false,
        "tls_server_name": null,
        "kv_path": null,
        "tls_verify": true
      },
      "kong": {},
      "consul": {
        "host": null,
        "port": null,
        "token": null,
        "timeout": null,
        "https": false,
        "kv_path": null
      }
    },
    "cert_type": "rsa",
    "tos_accepted": true,
    "fail_backoff_minutes": 5,
    "domains": [
      "mydomain.com"
    ],
    "renew_threshold_days": 14,
    "account_email": "myemail"
  }
}`

And this is my compose file(which I use to deploy the stack):
`
version: "3.8"
services:
  kong-database:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
    ports:
      - "5432:5432"
    networks:
      - kong-net

  kong-migration:
    image: kong:latest
    depends_on:
      - kong-database
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
    command: kong migrations bootstrap
    networks:
      - kong-net

  kong:
    image: kong:latest
    depends_on:
      - kong-database
      - kong-migration
    deploy:
      replicas: 3
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - 'KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl'
      - KONG_LUA_SSL_TRUSTED_CERTIFICATE=/etc/ssl/cert.pem
    ports:
      - "80:8000"
      - "443:8443"
      - '127.0.0.1:8001:8001'
      - '127.0.0.1:8444:8444'
    networks:
      - kong-net

networks:
  kong-net:
   external: true
`

**Comment by fffonion** [comment]
thanks you @iacapuca which version of kong gateway are you running?

**Comment by iacapuca** [comment]
> thanks you @iacapuca which version of kong gateway are you running?

The latest one, 2.2.1

**Comment by fffonion** [comment]
Ok, then it shouldn't have the cache bug. Are we running Kong in multiple nodes/containers? Since I saw you are using the `shm` storage and it won't propagate between different clusters. If so try to use `kong` storage.
(I do saw a `replica: 3` so i assume that's the case)

**Comment by iacapuca** [comment]
> Ok, then it shouldn't have the cache bug. Are we running Kong in multiple nodes/containers? Since I saw you are using the `shm` storage and it won't propagate between different clusters. If so try to use `kong` storage.
> (I do saw a `replica: 3` so i assume that's the case)

I'm so sorry, I just realized i was using `shm`, I have just changed to `kong` and it did worked just fine.
If I may ask, what would happen if I bring my Kong containers down? Would I still have some persistence of the certs after and bring them up again?

**Comment by fffonion** [comment]
> Would I still have some persistence of the certs after and bring them up again?

@iacapuca It will, with database mode the created cert are stored in Certificate and SNI entity, it will be persistent in kong's database.

**Comment by iacapuca** [comment]
Thank you very much for all the answers, I'll be closing this issue now.
