### ISSUE TITLE
How to disign port when create or renew certificate

### ISSUE THREAD

**Issue by garysdevil** [Kong/kong-plugin-acme#62]
How to disign port when create or renew certificate
![image](https://user-images.githubusercontent.com/41293784/103392452-f4ba7e00-4b58-11eb-9c31-baa64e064b01.png)

**Comment by fffonion** [comment]
@garysdevil the acme http-01 challenge requires port 80, you can't use a custom port for this. you will need to let kong to listen port 80 or use a load balancer that listens on port 80 and forward to kong.

**Comment by garysdevil** [comment]
> @garysdevil the acme http-01 challenge requires port 80, you can't use a custom port for this. you will need to let kong to listen port 80 or use a load balancer that listens on port 80 and forward to kong.

Got it

**Comment by garysdevil** [comment]
Can't use custom port
