### ISSUE TITLE
no corresponding response found for....

### ISSUE THREAD

**Issue by hgeorge89** [Kong/kong-plugin-acme#67]
Hello!

Im sorry if this problem has been resolved, but I haven't been able to fix it yet.
What happens is that I can successfully renew the certificate manually, but it automatically fails and I get a 404 error code back.
The following error logs occur to me:

```
[warn] 26#0: *22963418 [lua] http-01.lua:54: serve_challenge(): no corresponding response found for MyCRY_0K7bQ5rcf2wFGLBZ13KDNNywO24TKvSN-pBc8, client: 64.78.149.164, server: kong, request: "GET /.well-known/acme-challenge/MyCRY_0K7bQ5rcf2wFGLBZ13KDNNywO24TKvSN-pBc8 HTTP/1.1", host: "subdomain.demo.mydomain.com" 

"GET /.well-known/acme-challenge/MyCRY_0K7bQ5rcf2wFGLBZ13KDNNywO24TKvSN-pBc8 HTTP/1.1" 404 27 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
```

```
[lua] certificate.lua:38: log(): [ssl] failed to fetch SNI: failed to fetch 'my_server_ip SNI: [postgres] must not be an IP, context: ssl_certificate_by_lua*, client: 64.62.197.62, server: 0.0.0.0:8443
```

Thank you in advance for your answer!

**Comment by hgeorge89** [comment]
@fffonion 
Is it possible that it doesn't work for me due to the KONG version and has been fixed in later versions?
This is my KONG version: 2.1.4

**Comment by fffonion** [comment]
@hgeorge89 i would suggest to try a newer version of Kong. BTW `failed to fetch SNI` is an noise error
that doesn't affect this plugin, it's also fixed in later version of Kong.

**Comment by hgeorge89** [comment]
@fffonion 
OK
So then automatic certificate renewal doesn't work due to another problem?
Thank you in advance for your answer!

**Comment by fffonion** [comment]
@hgeorge89 Please try with a more recent version of Kong, the plugin itself has received bunch of bug fixes in between.

**Comment by hgeorge89** [comment]
@fffonion 
Thank you very much for the answers!
I close it.
