### ISSUE TITLE
route http to https redirect

### ISSUE THREAD

**Issue by lukasa1993** [Kong/kong-plugin-acme#7]
cant seem to make this work with 301 redirects on routes from http to https should i disable it? also does it need http method enabled on routes to work?

**Comment by fffonion** [comment]
Hi @lukasa1993 the route needs to match /.well-known/acme-challenge/ path in http protocol so the plugin can complete challenge. You will need to exclude that path from being 301 redirected.

**Comment by lukasa1993** [comment]
hmm so i manually add it and leave my existing routes as is ?

hmm can plugin do this also automatically? like just before verification to add such routes and then remove them?

**Comment by fffonion** [comment]
> hmm so i manually add it and leave my existing routes as is ?

correct. just create a route with such and don't associate with any service. the acme plugin will work like a request termination plugin on that specific path.

> hmm can plugin do this also automatically? like just before verification to add such routes and then remove them?

that is definitely possible to do as a plugin. but doesn't seem a good pattern to me. (actually the current logic to add/update sni/cert in this plugin is also hacky and i'm thinking of replacing it).

**Comment by lukasa1993** [comment]
whats wrong with it?


one more thing should it run dry-run first so if route isnt setup correctly it wont gir rate-limmiter

**Comment by fffonion** [comment]
you can use the staging API with very high rate limiting to test your setup by setting `config.api_url` to `https://acme-staging-v02.api.letsencrypt.org/`

**Comment by lukasa1993** [comment]
thank you

**Comment by fffonion** [comment]
Consider resolved, please reopen if you have any questions : )

**Comment by BogdanDarius** [comment]
I have a similar issue.
So i have two routes:
- One at "/" pointing to my service localhost:5000 with redirect 301
- One at "./well-known/acme-challenge/" separate from the service
I am using kong with docker so when I create a new container I use
```
-v /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
-e "KONG_LUA_SSL_TRUSTED_CERTIFICATE=/etc/ssl/certs/ca-certificates.crt"
```
The problem is that when I trigger the creation of certificate using 
```
curl https://mydomain.com
```
I get 
```
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html
```
Can you please point out what I am doing wrong.
Thanks in advance.

**Comment by fffonion** [comment]
@BogdanDarius the first time you access the url it's okay to ignore the certificate checking (by using `curl -k https://mydomain.com`) since Kong by default serves a self signed certificate. after the request goes through, kong will start apply certificate from let's encrypt and you don't need the `k` flag anymore.

**Comment by BogdanDarius** [comment]
@fffonion Thanks for response!
When I run it using insecure option -k I get two blank lines and then my api response.
The certificate is not issued that is the probleme.

**Comment by BogdanDarius** [comment]
@fffonion Thanks for response.
I was looking through docker logs here is what I get
```
"GET /.well-known/acme-challenge/etSIpDRB53YsrWXa6Spr7VQhdF-ejACccd_9Ee-3-1Y HTTP/1.1" 404 136 "MYDOMAIN/.well-known/acme-challenge/etSIpDRB53YsrWXa6Spr7VQhdF-ejACccd_9Ee-3-1Y" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
2020/05/16 20:26:18 [error] 32#0: *18807 [kong] handler.lua:104 failed to update certificate: could not create certificate: challenge invalid: http-01: invalid: Invalid response from MYDOMAIN/.well-known/acme-challenge/etSIpDRB53YsrWXa6Spr7VQhdF-ejACccd_9Ee-3-1Y [82.79.163.185]: "{\n  \"code\": 404,\n  \"type\": \"ResourceNotFoundException\",\n  \"message\": \"Requested resource is not found, please refer to API docum", context: ngx.timer, client: 79.118.9.191, server: 0.0.0.0:8443
```

**Comment by BogdanDarius** [comment]
> @BogdanDarius the first time you access the url it's okay to ignore the certificate checking (by using `curl -k https://mydomain.com`) since Kong by default serves a self signed certificate. after the request goes through, kong will start apply certificate from let's encrypt and you don't need the `k` flag anymore.

Got it working. Thanks!
